/* Generated By:JavaCC: Do not edit this line. testConstants.java */
package finalProject;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface testConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CLOSE = 5;
  /** RegularExpression Id. */
  int OPEN = 6;
  /** RegularExpression Id. */
  int OPENSQ = 7;
  /** RegularExpression Id. */
  int CLOSESQ = 8;
  /** RegularExpression Id. */
  int QUOTE = 9;
  /** RegularExpression Id. */
  int INCRESS = 10;
  /** RegularExpression Id. */
  int PLUS = 11;
  /** RegularExpression Id. */
  int DECRESS = 12;
  /** RegularExpression Id. */
  int MATHOP = 13;
  /** RegularExpression Id. */
  int LOGICOP = 14;
  /** RegularExpression Id. */
  int COMPAREOP = 15;
  /** RegularExpression Id. */
  int CHAR = 16;
  /** RegularExpression Id. */
  int DIGIT = 17;
  /** RegularExpression Id. */
  int SPECIAL = 18;
  /** RegularExpression Id. */
  int FOR = 19;
  /** RegularExpression Id. */
  int SWITCH = 20;
  /** RegularExpression Id. */
  int DEFAUL = 21;
  /** RegularExpression Id. */
  int IN = 22;
  /** RegularExpression Id. */
  int CASE = 23;
  /** RegularExpression Id. */
  int BREAK = 24;
  /** RegularExpression Id. */
  int PRINT = 25;
  /** RegularExpression Id. */
  int READ = 26;
  /** RegularExpression Id. */
  int DTYPE = 27;
  /** RegularExpression Id. */
  int WHILE = 28;
  /** RegularExpression Id. */
  int IF = 29;
  /** RegularExpression Id. */
  int ELSEIF = 30;
  /** RegularExpression Id. */
  int ELSE = 31;
  /** RegularExpression Id. */
  int DO = 32;
  /** RegularExpression Id. */
  int END = 33;
  /** RegularExpression Id. */
  int EQ = 34;
  /** RegularExpression Id. */
  int INT = 35;
  /** RegularExpression Id. */
  int DOUBLE = 36;
  /** RegularExpression Id. */
  int STR = 37;
  /** RegularExpression Id. */
  int BOOL = 38;
  /** RegularExpression Id. */
  int VAR = 39;
  /** RegularExpression Id. */
  int ENDPROGRAM = 40;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\")\"",
    "\"(\"",
    "\"[\"",
    "\"]\"",
    "\"\\\"\"",
    "\"++\"",
    "\"+\"",
    "\"--\"",
    "<MATHOP>",
    "<LOGICOP>",
    "<COMPAREOP>",
    "<CHAR>",
    "<DIGIT>",
    "<SPECIAL>",
    "\"for\"",
    "\"switch\"",
    "\"default\"",
    "\"in\"",
    "\"case\"",
    "\"break\"",
    "<PRINT>",
    "\"Console.ReadLine()\"",
    "<DTYPE>",
    "\"while\"",
    "\"if\"",
    "\"else if\"",
    "\"else\"",
    "\"do\"",
    "\";\"",
    "\"=\"",
    "<INT>",
    "<DOUBLE>",
    "<STR>",
    "<BOOL>",
    "<VAR>",
    "\"return 0;\"",
    "\"{\"",
    "\"}\"",
    "\":\"",
  };

}
